In [22]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import joblib

In [23]:
df = pd.read_csv("../data/crowd_data.csv")
df.head()

  route_id  hour day_type  is_holiday weather crowd_level
0      R18    10  Weekend           1    Rain      Medium
1       R1    17  Weekend           0    Rain      Medium
2      R19    12  Weekend           1   Clear         Low
3      R10    11  Weekday           0   Clear      Medium
4      R13     9  Weekend           0   Clear      Medium

In [24]:
label_encoders = {}

categorical_cols = ["route_id", "day_type", "weather", "crowd_level"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [25]:
df.head()

   route_id  hour  day_type  is_holiday  weather  crowd_level
0         9    10         1           1        1            2
1         0    17         1           0        1            2
2        10    12         1           1        0            1
3         1    11         0           0        0            2
4         4     9         1           0        0            2

In [26]:
X = df.drop("crowd_level", axis=1)
y = df["crowd_level"]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [28]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=12, n_estimators=200, random_state=42)

In [29]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7516666666666667

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.76      0.69        92
           1       0.86      0.88      0.87       384
           2       0.44      0.34      0.38       124

    accuracy                           0.75       600
   macro avg       0.64      0.66      0.65       600
weighted avg       0.74      0.75      0.74       600

In [31]:
feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feature_importance

hour          0.522555
route_id      0.269943
weather       0.071663
is_holiday    0.068987
day_type      0.066852
dtype: float64

In [32]:
joblib.dump(model, "../models/crowd_model.pkl")
joblib.dump(label_encoders, "../models/label_encoders.pkl")

['../models/label_encoders.pkl']